# Generated by Django 4.2.30 on 2026-06-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeInfluencerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('channel_name', models.CharField(blank=True, default='', max_length=100)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('video_title', models.CharField(blank=True, default='', max_length=160)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('cost_per_view', models.FloatField(default=0)),
                ('consultation_count', models.PositiveIntegerField(default=0)),
                ('contract_count', models.PositiveIntegerField(default=0)),
                ('cost_per_consultation', models.FloatField(default=0)),
                ('cost_per_contract', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='YoutubeAnalysis',
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='campaignperformance',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='campaignperformance',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='campaignperformance',
            name='signups',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ad_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='ad_copy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='consultation_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='contract_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='contracts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='cost_per_consultation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='cost_per_contract',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaignperformance',
            name='ctr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='marketing.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubeinfluenceranalysis',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_analyses', to='marketing.campaign'),
        ),
    ]
