# Generated by Django 4.2.30 on 2026-06-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_youtubeinfluenceranalysis_delete_youtubeanalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.URLField(blank=True, default='')),
                ('channel_id', models.CharField(blank=True, default='', max_length=120)),
                ('channel_name', models.CharField(blank=True, default='', max_length=120)),
                ('main_content', models.CharField(blank=True, default='', max_length=200)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('total_view_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('recent_video_count', models.PositiveIntegerField(default=0)),
                ('recent_avg_views', models.FloatField(default=0)),
                ('recent_median_views', models.FloatField(default=0)),
                ('recent_min_views', models.PositiveIntegerField(default=0)),
                ('recent_max_views', models.PositiveIntegerField(default=0)),
                ('recent_avg_likes', models.FloatField(default=0)),
                ('recent_avg_comments', models.FloatField(default=0)),
                ('subscriber_view_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel_name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.URLField(blank=True, default='')),
                ('channel_id', models.CharField(blank=True, default='', max_length=120)),
                ('channel_name', models.CharField(blank=True, default='', max_length=120)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('total_view_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('recent_video_count', models.PositiveIntegerField(default=0)),
                ('recent_avg_views', models.FloatField(default=0)),
                ('recent_median_views', models.FloatField(default=0)),
                ('recent_min_views', models.PositiveIntegerField(default=0)),
                ('recent_max_views', models.PositiveIntegerField(default=0)),
                ('subscriber_view_rate', models.FloatField(default=0)),
                ('expected_paid_amount', models.PositiveIntegerField(default=0)),
                ('avg_cost_per_view', models.FloatField(default=0)),
                ('median_cost_per_view', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeRecentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_videos', to='marketing.youtubechannelanalysis')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='youtube_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.youtubechannel'),
        ),
    ]
