# Generated by Django 4.2.14 on 2026-06-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_youtubechannel_youtubechannelanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, choices=[('브랜드 인지도', '브랜드 인지도'), ('상담 신청 증가', '상담 신청 증가'), ('가입 전환 증가', '가입 전환 증가'), ('이벤트 홍보', '이벤트 홍보')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='service_type',
            field=models.CharField(blank=True, choices=[('인터넷', '인터넷'), ('인터넷+TV', '인터넷+TV'), ('정수기 렌탈', '정수기 렌탈'), ('가전 렌탈', '가전 렌탈'), ('휴대폰', '휴대폰'), ('이사', '이사'), ('기타', '기타')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('검토중', '검토중'), ('협상중', '협상중'), ('보류', '보류'), ('완료', '완료'), ('협상실패', '협상실패')], default='검토중', max_length=50),
        ),
    ]
