# Generated by Django 4.2.14 on 2026-06-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_campaign_memo_campaign_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannelanalysis',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_analyses', to='marketing.campaign'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('컨택예정', '컨택예정'), ('컨택중', '컨택중'), ('진행중', '진행중'), ('보류', '보류'), ('완료', '완료'), ('컨택실패', '컨택실패')], default='컨택예정', max_length=50),
        ),
    ]
