# Generated by Django 4.2.14 on 2026-06-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_youtubechannelanalysis_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('code', models.SlugField(blank=True, default='', max_length=80, unique=True)),
                ('destination_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', '클릭'), ('consultation', '상담 신청'), ('contract', '가입')], default='click', max_length=30)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketing.trackinglink')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
