# Generated by Django 4.2.14 on 2026-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_trackinglink_conversionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='recent_latest_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
