# Generated by Django 4.2.14 on 2026-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_youtubechannelrecentvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_contract_cost', models.PositiveIntegerField(default=3000000)),
                ('cpv_good_max', models.PositiveIntegerField(default=30)),
                ('cpv_normal_max', models.PositiveIntegerField(default=50)),
                ('cpv_review_max', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Setting',
                'verbose_name_plural': 'Marketing Settings',
            },
        ),
    ]
